### ISSUE TITLE
OOM When trying to index large collections (>3M)

### ISSUE THREAD

**Issue by bclavie** [lightonai/pylate#160]
Hey @raphaelsty. I flagged this to Antoine, but when using PyLate and the boilerplate evaluation code in the examples, I hit consistent OOMs when trying to add documents to the Fastplaid index with MS Marco. NQ works fine, so the issue occurs somewhere between ~2.5M and 8.8M docs. Document length was set to 300, in bf16.

The error is consistently the same:

```
thread '<unnamed>' panicked at /root/.cache/puccinialin/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tch-0.20.0/src/wrappers/tensor_generated.rs:18198:27:
called `Result::unwrap()` on an `Err` value: Torch("CUDA out of memory. Tried to allocate 2.00 MiB. GPU 0 has a total capacity of 79.25 GiB of which 1.88 MiB is free. Including non-PyTorch memory, this process has 79.24 GiB memory in use. Of the allocated memory 76.40 GiB is allocated by PyTorch, and 2.34 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)\nException raised from malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:1498 (most recent call first):\nframe #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x7fe1a977eeb0 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)\nframe #1: <unknown function> + 0x3ca3b (0x7fe1a9bfda3b in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)\nframe #2: <unknown function> + 0x3cc05 (0x7fe1a9bfdc05 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)\nframe #3: <unknown function> + 0x3d15f (0x7fe1a9bfe15f in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)\nframe #4: <unknown function> + 0x15d64ad (0x7fe18905c4ad in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #5: at::detail::empty_strided_generic(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::Allocator*, c10::DispatchKeySet, c10::ScalarType) + 0x100 (0x7fe189057d00 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #6: at::detail::empty_strided_cuda(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ScalarType, std::optional<c10::Device>) + 0x85 (0x7fe14cb05475 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)\nframe #7: at::detail::empty_strided_cuda(c10::ArrayRef<long>, c10::ArrayRef<long>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>) + 0x6f (0x7fe14cb0560f in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)\nframe #8: at::native::empty_strided_cuda(c10::ArrayRef<long>, c10::ArrayRef<long>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>) + 0x39 (0x7fe14cd90ef9 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)\nframe #9: <unknown function> + 0x3294ad2 (0x7fe14f128ad2 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)\nframe #10: <unknown function> + 0x3294bcf (0x7fe14f128bcf in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)\nframe #11: at::_ops::empty_strided::redispatch(c10::DispatchKeySet, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>) + 0xf5 (0x7fe189fa0145 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #12: <unknown function> + 0x28bdaee (0x7fe18a343aee in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #13: at::_ops::empty_strided::call(c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>) + 0x20b (0x7fe189fee95b in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #14: <unknown function> + 0x19a4a97 (0x7fe18942aa97 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #15: at::native::_to_copy(at::Tensor const&, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, bool, std::optional<c10::MemoryFormat>) + 0x1590 (0x7fe189798a80 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #16: <unknown function> + 0x2aed68c (0x7fe18a57368c in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #17: at::_ops::_to_copy::redispatch(c10::DispatchKeySet, at::Tensor const&, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, bool, std::optional<c10::MemoryFormat>) + 0xf2 (0x7fe189c494d2 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #18: <unknown function> + 0x28ba68b (0x7fe18a34068b in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #19: at::_ops::_to_copy::redispatch(c10::DispatchKeySet, at::Tensor const&, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, bool, std::optional<c10::MemoryFormat>) + 0xf2 (0x7fe189c494d2 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #20: <unknown function> + 0x49975dc (0x7fe18c41d5dc in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #21: <unknown function> + 0x4997a3f (0x7fe18c41da3f in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #22: at::_ops::_to_copy::call(at::Tensor const&, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, bool, std::optional<c10::MemoryFormat>) + 0x23d (0x7fe189ceaf7d in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #23: at::native::to(at::Tensor const&, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, bool, bool, std::optional<c10::MemoryFormat>) + 0xee (0x7fe1897964fe in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #24: <unknown function> + 0x2be4c42 (0x7fe18a66ac42 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #25: at::_ops::to_dtype_layout::call(at::Tensor const&, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, bool, bool, std::optional<c10::MemoryFormat>) + 0x247 (0x7fe189e81e17 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)\nframe #26: <unknown function> + 0xefe84 (0x7fdf2c6c4e84 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/fast_plaid/fast_plaid_rust.cpython-312-x86_64-linux-gnu.so)\nframe #27: <unknown function> + 0xf2ba0 (0x7fdf2c6c7ba0 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/fast_plaid/fast_plaid_rust.cpython-312-x86_64-linux-gnu.so)\nframe #28: <unknown function> + 0xe215f (0x7fdf2c6b715f in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/fast_plaid/fast_plaid_rust.cpython-312-x86_64-linux-gnu.so)\nframe #29: <unknown function> + 0xaf435 (0x7fdf2c684435 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/fast_plaid/fast_plaid_rust.cpython-312-x86_64-linux-gnu.so)\nframe #30: <unknown function> + 0xb155f (0x7fdf2c68655f in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/fast_plaid/fast_plaid_rust.cpython-312-x86_64-linux-gnu.so)\nframe #31: <unknown function> + 0xb3b1c (0x7fdf2c688b1c in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/fast_plaid/fast_plaid_rust.cpython-312-x86_64-linux-gnu.so)\nframe #32: <unknown function> + 0xb456a (0x7fdf2c68956a in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/fast_plaid/fast_plaid_rust.cpython-312-x86_64-linux-gnu.so)\nframe #33: <unknown function> + 0xb25e0 (0x7fdf2c6875e0 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/fast_plaid/fast_plaid_rust.cpython-312-x86_64-linux-gnu.so)\nframe #34: <unknown function> + 0xb3f10 (0x7fdf2c688f10 in /home/ubuntu/relu-evals/.venv/lib/python3.12/site-packages/fast_plaid/fast_plaid_rust.cpython-312-x86_64-linux-gnu.so)\nframe #35: /home/ubuntu/relu-evals/.venv/bin/python() [0x1604f67]\nframe #36: _PyEval_EvalFrameDefault + 0x2d91 (0x1617251 in /home/ubuntu/relu-evals/.venv/bin/python)\nframe #37: /home/ubuntu/relu-evals/.venv/bin/python() [0x1613a00]\nframe #38: _PyEval_EvalFrameDefault + 0x11dd2 (0x1626292 in /home/ubuntu/relu-evals/.venv/bin/python)\nframe #39: PyEval_EvalCode + 0xe2 (0x1696e22 in /home/ubuntu/relu-evals/.venv/bin/python)\nframe #40: /home/ubuntu/relu-evals/.venv/bin/python() [0x16b6082]\nframe #41: /home/ubuntu/relu-evals/.venv/bin/python() [0x17e8413]\nframe #42: _PyRun_SimpleFileObject + 0x118 (0x17e8198 in /home/ubuntu/relu-evals/.venv/bin/python)\nframe #43: _PyRun_AnyFileObject + 0x42 (0x17e8050 in /home/ubuntu/relu-evals/.venv/bin/python)\nframe #44: /home/ubuntu/relu-evals/.venv/bin/python() [0x17e7f8a]\nframe #45: /home/ubuntu/relu-evals/.venv/bin/python() [0x17e7e9e]\nframe #46: Py_RunMain + 0x2e5 (0x1736bfb in /home/ubuntu/relu-evals/.venv/bin/python)\nframe #47: /home/ubuntu/relu-evals/.venv/bin/python() [0x1763ffa]\nframe #48: /home/ubuntu/relu-evals/.venv/bin/python() [0x1763ded]\nframe #49: <unknown function> + 0x29d90 (0x7fe1aa6dbd90 in /lib/x86_64-linux-gnu/libc.so.6)\nframe #50: __libc_start_main + 0x80 (0x7fe1aa6dbe40 in /lib/x86_64-linux-gnu/libc.so.6)\nframe #51: _start + 0x29 (0x17bb7e9 in /home/ubuntu/relu-evals/.venv/bin/python)\n")
```

Occurs on different machines, one with torch 2.6 and CUDA 12.4, and one with 2.8 and CUDA 12.8. Both using A100 80GBs.

(this is likely a FastPlaid issue, but opening it here as it's very much part of the pylate pipeline)

**Comment by raphaelsty** [comment]
Hi @bclavie thanks a lot for this, I'll dig into this asap, I'll find a way to reduce memory usage and which good default parameters could help reduce memory usage 😊

**Comment by raphaelsty** [comment]
Hi @bclavie, hope you are going well, 

Just released [a new version of fast-plaid](https://github.com/lightonai/fast-plaid/releases) which reduce the GPU VRAM usage of the index. It brings several improvements as well. 

Overall the CPU RAM usage won't be changed as both the centroids and the documents embeddings / queries embeddings are quite heavy.

 I will in the future add an option to further reduce GPU VRAM usage which will be disabled by default to fit all hardware but it will reduce speed for sure. At some point I'll work on memory mapping as well in order to further reduce the CPU RAM usage but this version should run fine already, at least I hope so 😊 

Pushing this new version to PyLate this week, we might make a release soon.

**Comment by NohTow** [comment]
Hey,
@raphaelsty did an amazing job working for memory usage on both index creation and search and I have no issue running all of BEIR with the latest versions of fast-plaid.
I am personally using 1.3.1.X as the 1.4.1 introduced a parameter to use even less memory but that is a bit slow in my test (and is the default, we'll update either fast-plaid default or PyLate accordingly).

FWIW on the H100 I just have to set the batch size to 1 << 17 (from the 1 << 18) because the search might OOM for the big datasets given our pretty generous search params (ndocs).
Also, to save more RAM, you can load the model if fp16/bf16. I advise to use fp16 for now because right now ST (and PyLate because I copied the behavior) transform BF16 embeddings to FP32, and even though fast-plaid use half, I think it might use a bit more VRAM for copy and stuff. I might fix PyLate to use FP16 embeddings when the model is BF16 (for np compatibility).

Code to load the model in fp16:
```python
model = models.ColBERT(
        model_name_or_path=model_name,
        model_kwargs={"torch_dtype": torch.float16},
    )
```
If you are using ModernBERT-based model, make sure the config of the model has do_query_expansion to false (or set it when initing the model), because FA embeddings for padding is 0 for BF16 (so very fine), but NaN for FP16 :')

Let me know if you need any help, I also have boilerplate that parallelize encoding across GPUs, which I've been using to run BEIR quickly. The search is also parallelized, only the indexing is done on a single GPU.
